### ISSUE TITLE
Difference between vite-plugin-svelte and svite

### ISSUE THREAD

**Issue by nym21** [intrnl/vite-plugin-svelte#1]
Hi,

I think I'd be good to add to the readme the difference between this library and svite, if you find the time of course.

Oh and great job !

**Comment by intrnl** [comment]
Ahh, this is the first time I've heard of svite, will probably check it out soon.

**Comment by intrnl** [comment]
Okay, I've checked it. I don't think there's anything worth mentioning other than slight difference in implementation details, and svite does mention this plugin as inspiration.

Hard to write this down on the README unfortunately :sweat_smile:

**Comment by nym21** [comment]
Okay sure ! Again, I just thought you should know about it haha
