### ISSUE TITLE
what is vite?

### ISSUE THREAD

**Issue by markfirmware** [intrnl/vite-plugin-svelte#3]

**Comment by intrnl** [comment]
[Vite](https://github.com/vitejs/vite) is a no-bundler bundler, where during development, instead of bundling your app, it would instead run a dev server that transforms files on the fly.

**Comment by markfirmware** [comment]
Thanks! Perhaps you might link to both svelte and vite in the readme.

**Comment by intrnl** [comment]
Sure.
