### ISSUE TITLE
How to make typescript work?

### ISSUE THREAD

**Issue by numfin** [intrnl/vite-plugin-svelte#5]
Hi, i found your plugin but cannot make it work with typescript. What should i do?

![image](https://user-images.githubusercontent.com/8134947/90701449-1e04fc80-e291-11ea-9414-5e12df44f6b0.png)

![image](https://user-images.githubusercontent.com/8134947/90701404-062d7880-e291-11ea-8694-68b0e8e4554e.png)

**Comment by intrnl** [comment]
You need to use [`svelte-preprocess`](https://github.com/sveltejs/svelte-preprocess) to get TS to work

**Comment by numfin** [comment]
@intrnl thank you for quick response. I just need to install it?
I installed it and dont know how to make it work :) sorry for dumb questions

**Comment by numfin** [comment]
@intrnl  thank you for quick response.
For others coming here:
![image](https://user-images.githubusercontent.com/8134947/90701807-48a38500-e292-11ea-8662-30010ca36d9f.png)

**Comment by intrnl** [comment]
🎉

**Comment by ozanmuyes** [comment]
By the way there's this beautiful article https://codechips.me/svelte-with-vitejs-typescript-tailwind/
